title: ESCARAMUZAS DE CAFÉ
description: Juego de mesa
author: Jonathan Prado

remote_theme: pages-themes/leap-day@v0.2.0
markdown: GFM
show_downloads: false

preferences:
- type: dropdown
  name: language
  label: Language
  description: Choose your preferred language.
  options:
  - label: English
    value: en
  - label: Español
    value: es

#share-links-active:
#  twitter: true
#  facebook: true
#  linkedin: true
